import os
from typing import Any

import boto3
import structlog
from src.api.agents.nlq_agent.state import NLQAgentState

logger = structlog.get_logger()

def fetch_catalog_context(state: NLQAgentState) -> dict[str, Any]:
    """
    Dynamically interrogates the AWS Glue Data Catalog to fetch schemas and metadata
    enriched by the Phase 3 Data Quality Agent.
    """
    database_name = os.getenv("GLUE_DATABASE", "dataplatform_dev_ai_catalog")
    logger.info("fetching_glue_metadata", database=database_name, query=state["user_query"])

    glue_client = boto3.client("glue", region_name=os.getenv("AWS_REGION", "us-east-1"))

    try:
        # Step 1: List tables within the specific AI Catalog
        # In a massive enterprise context, pass this list to
        # a simple LLM utility first to filter relevant tables
        tables_response = glue_client.get_tables(DatabaseName=database_name)
        tables: list[dict[str, Any]] = tables_response.get("TableList", [])

        context_chunks: list[str] = []
        target_tables: list[str] = []

        for table in tables:
            table_name = table["Name"]
            target_tables.append(table_name)

            # Extract descriptions generated by Phase 3 Steward Agent
            table_desc = table.get("Description", "No description available.")
            columns = table.get("StorageDescriptor", {}).get("Columns", [])

            column_definitions = []
            for col in columns:
                col_name = col["Name"]
                col_type = col["Type"]
                col_comment = col.get("Comment", "")
                column_definitions.append(f"  - {col_name} ({col_type}): {col_comment}")

            table_context= (
                f"Table: {table_name}\nDescription: {table_desc}\nColumns:\n"
                + "\n".join(column_definitions)
            )
            context_chunks.append(table_context)

        return {
            "catalog_context": "\n\n".join(context_chunks),
            "target_tables": target_tables,
            "error_trace": None
        }

    except Exception as e:
        logger.error("glue_metadata_extraction_failed", error=str(e))
        return {
            "catalog_context": "",
            "error_trace": f"Failed to fetch metadata context from Glue: {str(e)}"
        }
