locals {
  vpc_id             = data.terraform_remote_state.foundation.outputs.vpc_id
  private_subnet_ids = data.terraform_remote_state.foundation.outputs.private_subnet_ids
  step_function_arn  = data.terraform_remote_state.data_pipeline.outputs.step_function_arn
}

module "dynamodb_checkpoints" {
  source       = "../../../modules/dynamodb_state"
  table_name   = "langgraph-checkpoints-${var.environment}"
  billing_mode = "PAY_PER_REQUEST"
  tags         = var.tags
}

module "ai_dq_agent_compute" {
  source             = "../../../modules/ecs_fargate"
  project_name       = var.project_name
  environment        = var.environment
  vpc_id             = local.vpc_id
  private_subnet_ids = local.private_subnet_ids
  ecr_image_uri      = var.agent_ecr_image_uri
  dynamodb_table_arn = module.dynamodb_checkpoints.table_arn
  silver_bucket_arn  = "arn:aws:s3:::${data.terraform_remote_state.foundation.outputs.datalake_bucket_names["silver"]}"

  # Injecting environment variables into the container
  environment_variables = {
    ENVIRONMENT            = var.environment
    AWS_REGION             = var.aws_region
    SILVER_BUCKET_NAME     = data.terraform_remote_state.foundation.outputs.datalake_bucket_names["silver"]
    QUARANTINE_BUCKET_NAME = data.terraform_remote_state.foundation.outputs.datalake_bucket_names["quarantine"]
  }
}

module "eventbridge_trigger" {
  source                  = "../../../modules/eventbridge_ecs_trigger"
  project_name            = var.project_name
  environment             = var.environment
  step_function_arn       = local.step_function_arn
  ecs_cluster_arn         = module.ai_dq_agent_compute.cluster_arn
  ecs_task_definition_arn = module.ai_dq_agent_compute.task_definition_arn
  private_subnet_ids      = local.private_subnet_ids
  ecs_security_group_id   = module.ai_dq_agent_compute.security_group_id
}

# ==============================================================================
# EVENTBRIDGE TRIGGER (PHASE 2 -> PHASE 3 HANDOFF)
# ==============================================================================

resource "aws_cloudwatch_event_rule" "trigger_dq_agent" {
  name        = "${var.project_name}-${var.environment}-trigger-dq-agent"
  description = "Triggers the AI DQ Agent when Phase 2 Step Functions succeed."

  event_pattern = jsonencode({
    "source" : ["aws.states"],
    "detail-type" : ["Step Functions Execution Status Change"],
    "detail" : {
      "status" : ["SUCCEEDED"],
      "stateMachineArn" : [local.step_function_arn]
    }
  })
}

resource "aws_iam_role" "eventbridge_ecs_invoke_role" {
  name = "${var.project_name}-${var.environment}-eb-ecs-invoke-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [{
      Action    = "sts:AssumeRole",
      Effect    = "Allow",
      Principal = { Service = "events.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy" "eventbridge_ecs_invoke_policy" {
  name = "AllowEventBridgeToRunECS"
  role = aws_iam_role.eventbridge_ecs_invoke_role.id
  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect   = "Allow",
        Action   = "ecs:RunTask",
        Resource = "arn:aws:ecs:${var.aws_region}:*:task-definition/${var.project_name}-${var.environment}-dq-agent:*"
      },
      {
        Effect   = "Allow",
        Action   = "iam:PassRole",
        Resource = "*" # Allows passing the dynamic ECS roles generated by your module
      }
    ]
  })
}

resource "aws_cloudwatch_event_target" "ecs_dq_agent_target" {
  rule      = aws_cloudwatch_event_rule.trigger_dq_agent.name
  target_id = "TriggerDQAgentECS"
  arn       = module.ai_dq_agent_compute.cluster_arn
  role_arn  = aws_iam_role.eventbridge_ecs_invoke_role.arn

  ecs_target {
    task_definition_arn = replace(module.ai_dq_agent_compute.task_definition_arn, "/:\\d+$/", "")
    launch_type         = "FARGATE"

    network_configuration {
      subnets          = local.private_subnet_ids
      security_groups  = [module.ai_dq_agent_compute.security_group_id]
      assign_public_ip = false
    }
  }
}