name: 'dataplatform_transforms'
version: '1.0.0'
config-version: 2

profile: 'athena_gold'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dataplatform_transforms:
    gold:
      +materialized: table
      +table_type: iceberg
      +format: parquet