name: Deploy Phase 1 - Foundation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/environments/**/01-foundation/**'
      - 'terraform/01-foundation/**'
      - '.github/workflows/deploy-phase1.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/environments/**/01-foundation/**'
      - 'terraform/01-foundation/**'
      - 'github/workflows/deploy-phase1.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment (dev or prod)'
        required: true
        type: environment
        default: 'dev'

permissions:
  id-token: write 
  contents: read
  pull-requests: write 

env:
  TF_WORKING_DIR: 'terraform/01-foundation'
  DEPLOY_ENV: ${{ inputs.environment || 'dev' }}

jobs:
  validate-and-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config=../../terraform/environments/${{ env.DEPLOY_ENV }}/01-foundation/backend.conf

      - name: Terraform Format & Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -check
          terraform validate

      # Phase 1 Requirement: tfsec blocks PRs if buckets are public/unversioned
      - name: Security Scan (tfsec)
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          working_directory: ${{ env.TF_WORKING_DIR }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -no-color -var-file=../../terraform/environments/${{ env.DEPLOY_ENV }}/01-foundation/terraform.tfvars -out=tfplan  

  apply:
    needs: validate-and-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-role
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init  -backend-config=../../terraform/environments/${{ env.DEPLOY_ENV }}/01-foundation/backend.conf
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -no-color -var-file=../../terraform/environments/${{ env.DEPLOY_ENV }}/01-foundation/terraform.tfvars -out=tfplan  

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply tfplan
          
